# Pandas

All about pandas

In [ ]:
import numpy as np
import pandas as pd
!pip install gapminder
from gapminder import gapminder

In [5]:
height = np.array([1.79, 1.85, 1.95, 1.55])
weight = np.array([70, 80, 85, 65])
hw = np.array([height, weight]).transpose()

hw

array([[ 1.79, 70.  ],
       [ 1.85, 80.  ],
       [ 1.95, 85.  ],
       [ 1.55, 65.  ]])

In [ ]:
df = pd.DataFrame(hw , columns = ["height", "weight"]) 
print(df)

   height  weight
0    1.79    70.0
1    1.85    80.0
2    1.95    85.0
3    1.55    65.0

In [ ]:
df = pd.DataFrame(hw , columns = ["height", "weight"],
                  index = ["Peter", "Matilda", "Bee", "Bee"]) 
print(df)

         height  weight
Peter      1.79    70.0
Matilda    1.85    80.0
Bee        1.95    85.0
Bee        1.55    65.0

Can you extract:

0.   All weights
1.   Peter's height
2.   Bee's full info
3.   the average height
4.   get all persons with height greater than 180cm

### Gapminder

In [6]:
gapminder.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106


Tasks

* find the unique years
* get all rows with year 1952
* get all rows from 1952:1962
* get all rows from Afghanistan to Albania